apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pg2bo8phj-python 
  janus-idp.io/tekton: pg2bo8phj-python
  backstage.io/kubernetes-id: pg2bo8phj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pg2bo8phj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml